server:
  port: 8083
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mariadb://localhost:3307/inventory_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: user
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

kafka:
  topics:
    order-created: order.created
    payment-failed: payment.failed
    inventory-reserved: inventory.reserved
    inventory-reserve-failed: inventory.reserve.failed
    inventory-released: inventory.released
    inventory-confirmed: inventory.confirmed

outbox:
  scheduler:
    fixed-delay: 5000
